In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%cd '~/Documents/dataScienceIntensive/project/analysis'

/home/jdickerson/Documents/dataScienceIntensive/project/analysis

In [6]:
releases = pd.read_csv('../data/release_dates.csv')
releases = releases[(releases.season.notnull()) & (releases.episode_num.notnull())]
releases.sort_values(['title', 'season', 'episode_num']).head()

,title,year,episode_name,season,episode_num,country,date
3,"""#1 Single""",2006,Is the Grass Greener?,1,1,USA,2006-01-22
7,"""#1 Single""",2006,Window Shopping,1,2,USA,2006-01-29
5,"""#1 Single""",2006,The Rules of Dating,1,3,USA,2006-02-05
1,"""#1 Single""",2006,Cats and Dogs,1,4,USA,2006-02-12
2,"""#1 Single""",2006,Finishing a Chapter,1,5,USA,2006-02-19

In [7]:
english_speaking_titles = releases[(releases.country == 'USA') & (releases.year > 1990)]
english_speaking_titles.head()
len(english_speaking_titles)

290912

In [8]:
ratings = pd.read_csv('../data/ratings.csv')
ratings['rank'] = ( (ratings['votes'] / (ratings['votes'] + 25000)) * ratings['rating'] + 
                    (25000 / ((ratings['votes'] + 25000)))*6.9 
                  )
ratings.head()

,title,year,episode_name,season,episode_num,rating,votes,rank
0,"""#1 Single""",2006,NaN,NaN,NaN,6.2,62,6.898268
1,"""#7DaysLater""",2013,NaN,NaN,NaN,7.1,14,6.900112
2,"""#Bikerlive""",2014,NaN,NaN,NaN,7.4,10,6.900200
3,"""#BlackLove""",2015,NaN,NaN,NaN,6.8,30,6.899880
4,"""#ByMySide""",2012,NaN,NaN,NaN,5.7,14,6.899328

In [96]:
data = english_speaking_titles.merge(ratings, how='inner')

In [97]:
data.sort_values('rank', ascending=False).head()

,title,year,episode_name,season,episode_num,country,date,rating,votes,rank
10923,"""Breaking Bad""",2008,Ozymandias,5,14,USA,2013-09-15,10.0,70412,9.187733
10901,"""Breaking Bad""",2008,Felina,5,16,USA,2013-09-29,9.9,49967,8.899560
28392,"""Game of Thrones""",2011,Hardhome,5,8,USA,2015-05-31,9.9,39244,8.732576
28419,"""Game of Thrones""",2011,The Rains of Castamere,3,9,USA,2013-06-02,9.9,36981,8.689952
28412,"""Game of Thrones""",2011,The Lion and the Rose,4,2,USA,2014-04-13,9.7,23425,8.254466

In [98]:
writers = pd.read_csv('../data/writers.csv')
writers.head()

,title,year,episode_name,season,episode_num,name,type
0,"""The Lyricist Lounge Show""",2000,NaN,NaN,NaN,Michael 'babeepower' Viera,NaN
1,"""De Middeleeuwen""",2001,NaN,NaN,NaN,Jan 't Lam,scenario
2,"""Shortland Street""",1992,(#8.203),NaN,NaN,Michele A'Court,writer
3,"""The Kids of Degrassi Street""",1979,Chuck Makes a Choice,1,9,Susan A'Court,writer
4,"""The Kids of Degrassi Street""",1979,Liz Sits the Schlegels,1,13,Susan A'Court,writer

In [144]:
data = data.merge(writers)
data.sort_values('rank', ascending=False).head()

,title,year,episode_name,season,episode_num,country,date,rating,votes,rank,name,type
32542,"""Breaking Bad""",2008,Ozymandias,5,14,USA,2013-09-15,10.0,70412,9.187733,Vince Gilligan,created by
32543,"""Breaking Bad""",2008,Ozymandias,5,14,USA,2013-09-15,10.0,70412,9.187733,Moira Walley-Beckett,written by
32494,"""Breaking Bad""",2008,Felina,5,16,USA,2013-09-29,9.9,49967,8.899560,Vince Gilligan,created by
32495,"""Breaking Bad""",2008,Felina,5,16,USA,2013-09-29,9.9,49967,8.899560,Vince Gilligan,written by
84667,"""Game of Thrones""",2011,Hardhome,5,8,USA,2015-05-31,9.9,39244,8.732576,David Benioff,created by

In [145]:
data.groupby('name')['rank'].mean().sort_values(ascending=False).head(20)

name
David Benioff           7.568974
D.B. (II) Weiss         7.568974
George R.R. Martin      7.529039
Bryan Cogman            7.437436
Jeff McKibben           7.425404
Mark Gatiss             7.421171
Eric 'Giz' Gewirtz      7.353290
Peter Gould             7.348482
Nic Pizzolatto          7.338838
Dave (XXXIII) Hill      7.335868
George Mastras          7.334486
Gordon (XXI) Smith      7.331911
Steve (XII) Thompson    7.326697
Randolph Leon           7.306722
Luke Kalteux            7.270022
Vince Gilligan          7.262228
J. (V) Roberts          7.257896
Sam Catlin              7.250020
Steven Moffat           7.226605
Tony (XVIII) Moore      7.210473
Name: rank, dtype: float64

In [131]:
data.groupby(['title', 'season'])['rank'].mean().sort_values(ascending=False).tail(10)

title                  season
"Bionic Woman"         1         6.887521
"Family Guy"           12        6.885926
"The Girls Next Door"  2         6.884947
"Mater's Tall Tales"   3         6.884295
"Two and a Half Men"   12        6.882717
"Fear Itself"          1         6.881238
"Two and a Half Men"   9         6.880212
"The Girls Next Door"  1         6.877112
"Masters of Horror"    1         6.840910
                       2         6.837653
Name: rank, dtype: float64

In [149]:
data[data.title == None]

In [156]:
%pylab inline
data.loc[data.title == '"The Wire"'].groupby('season')['rank'].mean()

Populating the interactive namespace from numpy and matplotlib

season
1    7.000245
2    6.976815
3    6.984832
4    6.980943
5    6.983880
Name: rank, dtype: float64

In [160]:
data[data.name == "Matthew Weiner"].sort_values('date')

,title,year,episode_name,season,episode_num,country,date,rating,votes,rank,name,type
282286,"""The Naked Truth""",1995,"He Ain't Famous, He's My Brother",3,9,USA,1997-12-08,9.0,9,6.900756,Matthew Weiner,written by
282279,"""The Naked Truth""",1995,Day of the Locos,3,15,USA,1998-05-25,9.0,9,6.900756,Matthew Weiner,written by
23811,"""Becker""",1998,Stumble in the Bronx,2,8,USA,1999-11-08,7.9,30,6.901199,Matthew Weiner,written by
23634,"""Becker""",1998,Blind Curve,2,11,USA,1999-11-29,7.6,26,6.900727,Matthew Weiner,written by
23681,"""Becker""",1998,For Whom the Toll Calls,2,18,USA,2000-02-28,8.2,40,6.902077,Matthew Weiner,written by
23869,"""Becker""",1998,The Wrong Man,3,6,USA,2000-11-13,7.2,22,6.900264,Matthew Weiner,writer
23773,"""Becker""",1998,Pretty Poison,3,14,USA,2001-02-12,7.4,25,6.900500,Matthew Weiner,writer
23863,"""Becker""",1998,The Ugly Truth,3,17,USA,2001-03-05,7.5,25,6.900599,Matthew Weiner,writer
23775,"""Becker""",1998,Psycho Therapy,4,1,USA,2001-10-01,7.9,24,6.900959,Matthew Weiner,written by
23839,"""Becker""",1998,The Ghost of Christmas Presents,4,10,USA,2001-12-10,7.3,25,6.900400,Matthew Weiner,written by
23871,"""Becker""",1998,"Too Much, Too Late",4,19,USA,2002-04-15,7.1,18,6.900144,Matthew Weiner,writer
13109,"""Andy Richter Controls the Universe""",2002,The Maid Man,2,8,USA,2003-01-12,6.5,26,6.899584,Matthew Weiner,writer
292733,"""The Sopranos""",1999,Rat Pack,5,2,USA,2004-03-14,8.6,1036,6.967645,Matthew Weiner,written by
292739,"""The Sopranos""",1999,Sentimental Education,5,6,USA,2004-04-11,8.4,1000,6.957692,Matthew Weiner,written by
292786,"""The Sopranos""",1999,Unidentified Black Males,5,9,USA,2004-05-02,8.8,1059,6.977213,Matthew Weiner,written by
292774,"""The Sopranos""",1999,The Test Dream,5,11,USA,2004-05-16,8.5,1417,6.985824,Matthew Weiner,written by
292697,"""The Sopranos""",1999,Mayham,6,3,USA,2006-03-26,8.7,1114,6.976786,Matthew Weiner,written by
292691,"""The Sopranos""",1999,Luxury Lounge,6,7,USA,2006-04-23,8.4,1085,6.962392,Matthew Weiner,written by
292709,"""The Sopranos""",1999,Moe n' Joe,6,10,USA,2006-05-14,8.4,1007,6.958081,Matthew Weiner,written by
292678,"""The Sopranos""",1999,Kaisha,6,12,USA,2006-06-04,8.4,1130,6.964868,Matthew Weiner,written by
292744,"""The Sopranos""",1999,Soprano Home Movies,6,13,USA,2007-04-08,8.9,1357,7.002971,Matthew Weiner,written by
292606,"""The Sopranos""",1999,Chasing It,6,16,USA,2007-04-29,8.2,1119,6.955695,Matthew Weiner,written by
292682,"""The Sopranos""",1999,Kennedy and Heidi,6,18,USA,2007-05-13,9.0,1496,7.018569,Matthew Weiner,written by
292749,"""The Sopranos""",1999,The Blue Comet,6,20,USA,2007-06-03,9.4,1780,7.066169,Matthew Weiner,written by
131601,"""Mad Men""",2007,Smoke Gets in Your Eyes,1,1,USA,2007-07-19,8.2,2028,6.997543,Matthew Weiner,created by
131602,"""Mad Men""",2007,Smoke Gets in Your Eyes,1,1,USA,2007-07-19,8.2,2028,6.997543,Matthew Weiner,written by
131520,"""Mad Men""",2007,Ladies Room,1,2,USA,2007-07-26,7.6,1458,6.938574,Matthew Weiner,written by
131519,"""Mad Men""",2007,Ladies Room,1,2,USA,2007-07-26,7.6,1458,6.938574,Matthew Weiner,created by
131545,"""Mad Men""",2007,Marriage of Figaro,1,3,USA,2007-08-02,7.7,1347,6.940900,Matthew Weiner,created by
131557,"""Mad Men""",2007,New Amsterdam,1,4,USA,2007-08-09,8.0,1257,6.952660,Matthew Weiner,created by
...,...,...,...,...,...,...,...,...,...,...,...,...
131494,"""Mad Men""",2007,Favors,6,11,USA,2013-06-09,8.7,816,6.956895,Matthew Weiner,written by
131693,"""Mad Men""",2007,The Quality of Mercy,6,12,USA,2013-06-16,8.6,756,6.949899,Matthew Weiner,created by
131514,"""Mad Men""",2007,In Care Of,6,13,USA,2013-06-23,9.2,1040,6.991859,Matthew Weiner,written by
131513,"""Mad Men""",2007,In Care Of,6,13,USA,2013-06-23,9.2,1040,6.991859,Matthew Weiner,created by
131723,"""Mad Men""",2007,Time Zones,7,1,USA,2014-04-13,8.1,923,6.942727,Matthew Weiner,written by
131722,"""Mad Men""",2007,Time Zones,7,1,USA,2014-04-13,8.1,923,6.942727,Matthew Weiner,created by
131453,"""Mad Men""",2007,A Day's Work,7,2,USA,2014-04-20,8.5,812,6.950333,Matthew Weiner,created by
131454,"""Mad Men""",2007,A Day's Work,7,2,USA,2014-04-20,8.5,812,6.950333,Matthew Weiner,written by
131498,"""Mad Men""",2007,Field Trip,7,3,USA,2014-04-27,8.7,852,6.959322,Matthew Weiner,written by
131497,"""Mad Men""",2007,Field Trip,7,3,USA,2014-04-27,8.7,852,6.959322,Matthew Weiner,created by
131679,"""Mad Men""",2007,The Monolith,7,4,USA,2014-05-04,8.6,755,6.949835,Matthew Weiner,created by
131699,"""Mad Men""",2007,The Runaways,7,5,USA,2014-05-11,8.6,822,6.954117,Matthew Weiner,created by
131700,"""Mad Men""",2007,The Runaways,7,5,USA,2014-05-11,8.6,822,6.954117,Matthew Weiner,written by
131703,"""Mad Men""",2007,The Strategy,7,6,USA,2014-05-18,9.0,908,6.973599,Matthew Weiner,created by
131733,"""Mad Men""",2007,Waterloo,7,7,USA,2014-05-25,9.5,1373,7.035358,Matthew Weiner,created by
131734,"""Mad Men""",2007,Waterloo,7,7,USA,2014-05-25,9.5,1373,7.035358,Matthew Weiner,written by
131585,"""Mad Men""",2007,Severance,7,8,USA,2015-04-05,8.4,901,6.952179,Matthew Weiner,written by
131584,"""Mad Men""",2007,Severance,7,8,USA,2015-04-05,8.4,901,6.952179,Matthew Weiner,created by
131561,"""Mad Men""",2007,New Business,7,9,USA,2015-04-12,8.1,746,6.934770,Matthew Weiner,written by
131560,"""Mad Men""",2007,New Business,7,9,USA,2015-04-12,8.1,746,6.934770,Matthew Weiner,created by
131644,"""Mad Men""",2007,The Forecast,7,10,USA,2015-04-19,8.5,777,6.948229,Matthew Weiner,created by
131645,"""Mad Men""",2007,The Forecast,7,10,USA,2015-04-19,8.5,777,6.948229,Matthew Weiner,written by
131719,"""Mad Men""",2007,Time & Life,7,11,USA,2015-04-26,9.1,833,6.970940,Matthew Weiner,written by
131718,"""Mad Men""",2007,Time & Life,7,11,USA,2015-04-26,9.1,833,6.970940,Matthew Weiner,created by
131530,"""Mad Men""",2007,Lost Horizon,7,12,USA,2015-05-03,9.1,894,6.975956,Matthew Weiner,created by
131531,"""Mad Men""",2007,Lost Horizon,7,12,USA,2015-05-03,9.1,894,6.975956,Matthew Weiner,written by
131673,"""Mad Men""",2007,The Milk and Honey Route,7,13,USA,2015-05-10,9.2,1000,6.988462,Matthew Weiner,created by
131674,"""Mad Men""",2007,The Milk and Honey Route,7,13,USA,2015-05-10,9.2,1000,6.988462,Matthew Weiner,written by
131572,"""Mad Men""",2007,Person to Person,7,14,USA,2015-05-17,9.3,1724,7.054827,Matthew Weiner,written by
131571,"""Mad Men""",2007,Person to Person,7,14,USA,2015-05-17,9.3,1724,7.054827,Matthew Weiner,created by

In [175]:
data.loc[data['type'].str.contains('writ').fillna(False), 'Newtype'] = 'writer-ish'

In [176]:
data.loc[data['type'].str.contains('creat').fillna(False), 'Newtype'] = 'creator-ish'

In [177]:
len(data[data.Newtype.notnull()])

227693

In [179]:
len(data[data['Newtype'] == 'writer-ish'].name.value_counts())

9361